name: Update RSS Feed

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Mutual Fund page
        run: |
          curl -s -H "User-Agent: Mozilla/5.0 (RSS Updater)" \
            https://www.business-standard.com/markets/mutual-fund \
            -o bs.html

      - name: Generate RSS XML
        run: |
          python3 - <<'PY'
          import re, html, datetime
          from datetime import timezone, timedelta, datetime as dt

          # Read downloaded HTML
          with open("bs.html", encoding="utf-8", errors="ignore") as f:
              page = f.read()

          # Capture article URLs and titles more reliably
          pattern = re.compile(
              r'href="(/markets/mutual-fund/[^"]+)"[^>]*>\s*([^<]{10,200})</a>',
              re.I
          )
          items = re.findall(pattern, page)

          # Deduplicate and keep 15 newest
          seen, dedup = set(), []
          for href, title in items:
              if href not in seen:
                  seen.add(href)
                  dedup.append((href, title.strip()))
          dedup = dedup[:15]

          IST = timezone(timedelta(hours=5, minutes=30))
          now = dt.now(IST).strftime("%a, %d %b %Y %H:%M:%S %z")

          def cdata(t): return f"<![CDATA[{t}]]>"

          xml = []
          xml.append('<?xml version="1.0" encoding="UTF-8"?>')
          xml.append('<rss version="2.0">')
          xml.append('<channel>')
          xml.append(f'  <title>{cdata("Business Standard — Mutual Funds (Unofficial)")}</title>')
          xml.append('  <link>https://www.business-standard.com/markets/mutual-fund</link>')
          xml.append(f'  <description>{cdata("Auto-updated feed from Business Standard Mutual Fund page")}</description>')
          xml.append('  <language>en-IN</language>')
          xml.append(f'  <lastBuildDate>{now}</lastBuildDate>')
          xml.append('  <ttl>60</ttl>')

          for href, title in dedup:
              link = "https://www.business-standard.com" + href
              title = html.unescape(title)
              xml.append('  <item>')
              xml.append(f'    <title>{cdata(title)}</title>')
              xml.append(f'    <link>{link}</link>')
              xml.append(f'    <guid>{link}</guid>')
              xml.append(f'    <pubDate>{now}</pubDate>')
              xml.append(f'    <description>{cdata(title)}</description>')
              xml.append('  </item>')

          xml.append('</channel></rss>')
          with open("business-standard-mutual-funds.xml", "w", encoding="utf-8") as f:
              f.write("\n".join(xml))
          PY
